# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: Cargo.lock
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: \.rs$
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh

  - repo: https://github.com/AndrejOrsula/pre-commit-cargo
    rev: 0.3.0
    hooks:
      - id: cargo-fmt
      - id: cargo-update
      - id: cargo-clippy
        args: ["--all-targets", "--all-features", "--", "--deny=warnings"]
      - id: cargo-check
        args: ["--all-targets", "--all-features"]
      - id: cargo-test
        args: ["--all-targets"]
      - id: cargo-test-doc
        args: ["--all-features"]
      - id: cargo-doc
        args: ["--no-deps", "--document-private-items"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "crate"]
        exclude: Cargo.lock|input/.*|aoc2023/.*/day15.rs
